# Generated by Django 3.2.8 on 2021-11-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_catagory_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Zipcode',
            new_name='zipcode',
        ),
    ]
